name: flutter_quill_extensions_lite
description: Flutter package that provides additional features and enhancements to the `flutter_quill` package,
version: 1.0.0
homepage: https://github.com/Abbas1Hussein/flutter_quill_extensions_lite

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^7.2.19
  file_picker: ^5.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
